[package]
name = "rx"
version = "0.1.6"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
color-print = "0.3.7"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
